services:
  - type: web
    name: bi-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: FRONTEND_URL
        sync: false 